#! /bin/sh -ve

ovs-ofctl add-flow br0 \
    "table=0, dl_src=01:00:00:00:00:00/01:00:00:00:00:00, actions=drop"

ovs-ofctl add-flow br0 \
    "table=0, dl_dst=01:80:c2:00:00:00/ff:ff:ff:ff:ff:f0, actions=drop"

ovs-ofctl add-flow br0 "table=0, priority=0, actions=resubmit(,1)"

ovs-appctl --verbose --log-file=/home/shengliu/Workspace/log/log.txt ofproto/trace br0 in_port=1,dl_dst=01:80:c2:00:00:05
